  name: 'MyREDAXO Installer Action'
  author: FriendsOfREDAXO
  description: 'GitHub Action for MyREDAXO Installer'
  branding:
    icon: upload-cloud
    color: blue
  inputs:
      myredaxo-username:
          description: 'MyREDAXO username.'
          required: true
      myredaxo-api-key:
          description: 'MyREDAXO API Key.'
          required: true
      description:
          description: 'Package release version description.'
          default: ${{ github.event.release.body }}
          required: false
      cwd:
          description: 'Working directory where the package is located.'
          default: '.'
          required: false
      version:
          description: 'Package release version.'
          default: ${{ github.event.release.tag_name }}
          required: false
  runs:
    using: 'node16'
    main: 'dist/index.js'
