name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  build-tsc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false

    name: Build for node 16
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run build

  build-action:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.pull_request.draft == false && github.event_name != 'push' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' && 1 || 0 }}
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo

    name: Release Build for node 16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run release
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'rebuild action'
          file_pattern: 'dist/*'
          commit_user_name: rex-bot
          commit_user_email: rex-bot@users.noreply.github.com
          add_options: '-u --renormalize'
